### PR TITLE
Added a few languages/compilers

### PR DESCRIPTION
**Pull request by Asmageddon**
New languages are MoonScript, Julia, new compilers are GNU Pascal, Mono,
LLVM llc, Dart VM

### CODE REVIEW

**Comment by mohd-akram** [comment]
Thanks for the suggestions! I maintain the compilers list [here](https://github.com/mohd-akram/compilers/blob/master/src/compilers.coffee) and have added them to it.

**Comment by Asmageddon** [comment]
Ahh, dang. Didn't know, I don't often(ever) do webdev stuff.

I know this might not be the place for it, but I feel like it could be cool to have various execution platforms included as entities in the graph, so that JVM is a thing of its own, as would be the Python VM and so on, since JIT isn't exactly compiling everything down to machine code(you'd expect things that compile to it to be native standalone executables), but well, that's just me complaining.

**Comment by mohd-akram** [comment]
Yeah, I thought about that too. On the one hand, it would be nice to have everything in the graph compile to "Machine Code", but on the other hand it does feel a bit disingenuous. I'm thinking of maybe adding a "JIT Code" language to make this distinction. There's definitely a lot of cool ideas that can be implemented here.

**Comment by Asmageddon** [comment]
What about having the final target be the "platform", and platforms simply being marked as native/JITed/VM?

**Comment by mohd-akram** [comment]
Seems like that could work, I would have to play around with the idea to see if it fits as VM is the odd one out here (and also overlaps with JIT in some cases). Might be better if this was implemented as a different view with groupings.

**Comment by Asmageddon** [comment]
Well, JIT is usually a VM/interpreter, just one that compiles some or all of the code to machine code on the go, it rarely produces standalone code.

**Pull request closed without merging**
